hc = require 'lib.hc'
require 'math'
require 'assets.sprites'
require 'assets.animations'
require 'assets.sounds'
require 'assets.fonts'

require 'src.util'
require 'src.fps'
require 'src.controller'
require 'src.collisions'
require 'src.level'
require 'src.ships'
require 'src.gui'
require 'src.screens'
require 'src.countdown'
require 'src.spawns'
require 'src.bounds'
require 'src.bullets'
require 'src.splash'
require 'src.explosions'
require 'src.minimap'
require 'src.mines'
require 'src.tornadoes'
require 'src.powerups'
require 'src.background'
require 'src.playerselectors'
require 'src.islands'

require 'src.gamestates.gamestates'
require 'src.gamestates.game'
require 'src.gamestates.pregame'
require 'src.gamestates.postgame'